### ISSUE TITLE
Code release plan

### ISSUE THREAD

**Issue by LucioSunj** [wen-yuan-zhang/VolumeRenderingPriors#1]
Hi! Thanks for your wonderful project!

Could you please provide an overview of the code release schedule?

Thank you very much!

**Comment by wen-yuan-zhang** [comment]
Thanks for your attention. The code will be released before eccv main conference.

**Comment by LucioSunj** [comment]
> Thanks for your attention. The code will be released before eccv main conference.

Thank you very much!
